swagger:
  info:
    title: "IMP NFT Marketplace API Documentation - IMP NFT App"
    description: "This is the main API contains most of the assets."
    termsOfService: "http://www.example.org/terms/"
    contact:
      email: ""
    version: "1.0"
  host: "localhost:8080"
  basePath: "/api/v1"
  schemes:
    - "http"
    - "https"
  consumes:
    - "application/json"
  produces:
    - "application/json"